/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/dorat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dora(props) {
  const { nodes, materials } = useGLTF('models/dorat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0.geometry} material={nodes.geometry_0.material} />
    </group>
  )
}

useGLTF.preload('models/dorat.glb')
