/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/dora.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Environment } from "@react-three/drei";

export function Dora(props) {
  const { nodes, materials } = useGLTF('./models/dora.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('./model/dora.glb')
