/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/kendrik.glb 
*/

import React, { useRef } from 'react'
import { Text3D, useGLTF, 
  Environment
 } from '@react-three/drei'

export function Kendrik(props) {
  const { nodes, materials } = useGLTF('./models/kendrik.glb')
  return (
    <group {...props} dispose={null}>
            <Environment files="./assets/sky.exr" background />

      
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('./models/kendrik.glb')
